- name: Deploy to Tomcat 
  hosts: web
  become: yes
  
  tasks:
  
  	- name: copy WAR file to tomcat
  	  copy:
  	  
  	  src: "/var/snap/jenkins/5022/workspace/MyAnsible/target/MyAnsible.war"
  	  dest: "/opt/tomcat/webapps/MyAnsible.war"
  	  remote_src: no
  	  
  	- name: Restart Tomcat Manually
  	  shell: |
  	    /opt/tomcat/bin/shutdown.sh || true
  	    sleep 5
  	    /opt/tomcat/bin/startup.sh 
  	  
  	  
